create table public."Application_Log" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "SessionID" text null,
  "TransactionID" text null,
  "ParentTransactionID" text null,
  "Category" text null,
  "Endpoint" text null,
  "RequestPayload" text null,
  "ResponsePayload" text null,
  "Exception" text null,
  "ExceptionStackTrace" text null,
  "RelatedTo" text null,
  "Status" text null,
  constraint Application_Log_pkey primary key (id)
) TABLESPACE pg_default;
